CREATE SERVER AUDIT GirisKontrolAudit
TO FILE (FILEPATH = 'C:\SQLAudit\' );

ALTER SERVER AUDIT GirisKontrolAudit WITH (STATE = ON);

CREATE SERVER AUDIT SPECIFICATION GirisKontrolSpec
FOR SERVER AUDIT GirisKontrolAudit
ADD (SUCCESSFUL_LOGIN_GROUP),
ADD (FAILED_LOGIN_GROUP)
WITH (STATE = ON);
